extern bool executeOpen(void);
extern bool executeClose(void);
extern bool executeLock(void);
extern bool executeUnlock(void);
extern bool executeGet(void);
extern bool executeDrop(void);
extern bool executeAsk(void);
extern bool executeGive(void);
extern bool executeInventory(void);
